Update docker-compose.yaml

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,94 +1,108 @@
-version: '3.8'
-services:
-  db:
-    image: postgres:13
-    environment:
-      POSTGRES_DB: ${DB_NAME}
-      POSTGRES_PASSWORD: ${DB_PASSWORD}
-      POSTGRES_USER: ${DB_USER}
-      PGDATA: /var/lib/postgresql/data/pgdata
-    ports:
-      - "5432:5432"
-    volumes:
-      - DB_VOLUME:/var/lib/postgresql/data/pgdata
-    networks:
-      agent_network:
-        aliases:
-          - ${DB_HOST}
-      traefik_public:
-        aliases:
-          - ${DB_HOST}
+#!/bin/bash
 
-  odoo:
-    image: odoo:16.0-20250311
-    depends_on:
-      - db
-    environment:
-      DB_HOST: ${DB_HOST}
-      DB_NAME: ${DB_NAME}
-      DB_USER: ${DB_USER}
-      DB_PASSWORD: ${DB_PASSWORD}
-      EXPIRATION_DATE: ${EXPIRATION_DATE}
-      ENTERPRISE_CODE: ${ENTERPRISE_CODE}
-      ADDONS_PATH: ${ADDONS_PATH}
-      DATA_DIR: ${DATA_DIR}
-      ADMIN_PASSWD: ${ADMIN_PASSWD}
-      DB_MAXCONN: ${DB_MAXCONN}
-      DB_SSLMODE: ${DB_SSLMODE}
-      HTTP_ENABLE: ${HTTP_ENABLE}
-      LIMIT_MEMORY_HARD: ${LIMIT_MEMORY_HARD}
-      LIMIT_MEMORY_SOFT: ${LIMIT_MEMORY_SOFT}
-      LIMIT_TIME_CPU: ${LIMIT_TIME_CPU}
-      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
-      LOG_LEVEL: ${LOG_LEVEL}
-      PROXY_MODE: ${PROXY_MODE}
-      SERVER_WIDE_MODULES: ${SERVER_WIDE_MODULES}
-    volumes:
-      - ODOO_VOLUME_NAME:/var/lib/odoo
-      - ODOO_CONFIG_VOLUME_NAME:/etc/odoo
-      - ODOO_ADDONS_VOLUME_NAME:/mnt/extra-addons
-      - ODOO_ENTERPRISE_ADDONS_VOLUME_NAME:/mnt/enterprise-addons
-      - INIT_SCRIPT_VOLUME:/init-script
-      - INIT_DB_SQL_VOLUME:/init-db
-    user: root
-    entrypoint: ["/bin/sh", "-c", "cp /init-script/init-script.sh /init-script.sh && cp /init-db/init-db.sql /init-db.sql && chmod +x /init-script.sh && /init-script.sh"]
-    networks:
-      - agent_network
-      - traefik_public
-    deploy:
-      labels:
-        - "traefik.enable=true"
-        - "traefik.http.routers.odoo.rule=Host(`${WEB_HOST}`)"
-        - "traefik.http.routers.odoo.entrypoints=websecure"
-        - "traefik.http.routers.odoo.tls.certresolver=le"
-        - "traefik.http.services.odoo.loadbalancer.server.port=${WEB_PORT}"
+# Verificar si la carpeta /mnt/enterprise-addons/ está vacía
+if [ "$(ls -A /mnt/enterprise-addons/)" ]; then
+    echo "La carpeta /mnt/enterprise-addons/ ya contiene archivos. No se clonará el repositorio."
+else
+    # Clonar la rama 16.0 del repositorio Odoo-Enterprise
+    command -v git &>/dev/null || { 
+        echo "Git no está instalado. Instalando git..."; 
+        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git; 
+    }
+    
+    echo "Clonando el repositorio Odoo-Enterprise..."
+    git clone https://github.com/LMiguelGJ/OdooCluster16.git
+    
+    echo "Moviendo los addons a /mnt/enterprise-addons/..."
+    cd Odoo-Enterprise
+    mv addons/* /mnt/enterprise-addons/
+    echo "Limpiando el directorio clonado..."
+    cd ..
+    rm -rf Odoo-Enterprise
+fi
 
-networks:
-  traefik_public:
-    external: true
-    attachable: true
-  agent_network:
-    external: true
+# Modificar el archivo SQL antes de ejecutarlo usando awk
+echo "Modificando el archivo SQL.."
+awk -v exp_date="$EXPIRATION_DATE" -v ent_code="$ENTERPRISE_CODE" '
+{
+  gsub(/v_expiration_date TIMESTAMP := '\''[^'\'']*'\'';/, "v_expiration_date TIMESTAMP := '\''" exp_date "'\'';");
+  gsub(/v_enterprise_code TEXT := '\''[^'\'']*'\'';/, "v_enterprise_code TEXT := '\''" ent_code "'\'';");
+  print
+}' init-db.sql > temp.sql && cp temp.sql init-db.sql && rm temp.sql
 
-volumes:
-  DB_VOLUME:
-    external: true
-    name: DB_VOLUME_${CLIENT_NAME}
-  ODOO_VOLUME_NAME:
-    external: true
-    name: ODOO_VOLUME_${CLIENT_NAME}
-  ODOO_CONFIG_VOLUME_NAME:
-    external: true
-    name: ODOO_CONFIG_VOLUME_${CLIENT_NAME}
-  ODOO_ADDONS_VOLUME_NAME:
-    external: true
-    name: ODOO_ADDONS_VOLUME_${CLIENT_NAME}
-  ODOO_ENTERPRISE_ADDONS_VOLUME_NAME:
-    external: true
-    name: ODOO_ENTERPRISE_ADDONS_VOLUME_${CLIENT_NAME}
-  INIT_SCRIPT_VOLUME:
-    external: true
-    name: INIT_SCRIPT_VOLUME_${CLIENT_NAME}
-  INIT_DB_SQL_VOLUME:
-    external: true
-    name: INIT_DB_SQL_VOLUME_${CLIENT_NAME}
+
+# Ruta de configuración de Odoo
+ODOO_CONF="/etc/odoo/odoo.conf"
+TEMP_CONF="/etc/odoo/temp_odoo.conf"
+
+# Crear un nuevo archivo de configuración temporal con la sección [options]
+echo "[options]" > "$TEMP_CONF"
+
+# Leer todas las variables de entorno excluyendo las críticas
+env | grep -vE '^(PATH|HOSTNAME|TERM|SHELL|USER|PWD|HOME|SHLVL|LOGNAME|_|WEB_PORT|WEB_HOST|WEB_BUILD|EXPIRATION_DATE|ENTERPRISE_CODE)' | while IFS= read -r line; do
+    # Validar que la línea no esté vacía
+    if [ -n "$line" ]; then
+        # Convertir clave a minúscula, agregar espacios alrededor del '=', y escribir en el archivo temporal
+        key=$(echo "$line" | cut -d= -f1 | tr '[:upper:]' '[:lower:]')
+        value=$(echo "$line" | cut -d= -f2-)
+        echo "$key = $value" >> "$TEMP_CONF"
+    fi
+done
+
+# Reemplazar el archivo de configuración original con el temporal
+mv "$TEMP_CONF" "$ODOO_CONF"
+
+
+# Ejecutar Odoo
+echo "Iniciando Odoo..."
+sleep 5
+# Iniciar Odoo en modo "stop-after-init"
+echo "Iniciando Odoo y esperando que cargue todos los módulos..."
+/usr/bin/odoo -c /etc/odoo/odoo.conf -u all --stop-after-init &  
+ODOO_PID=$!
+
+# Esperar a que Odoo termine
+echo "Esperando que Odoo finalice su carga y se detenga..."
+wait $ODOO_PID
+
+if [ $? -eq 0 ]; then
+    echo "Odoo se ha detenido correctamente."
+else
+    echo "Error: Odoo no se detuvo correctamente." 
+    exit 1
+fi
+
+# Función para ejecutar comandos SQL con reintentos
+execute_sql_with_retries() {
+  local max_retries=5
+  local retry_interval=10
+  local attempt=1
+
+  while [ $attempt -le $max_retries ]
+  do
+    echo "Intento $attempt de $max_retries para ejecutar comandos SQL en la base de datos..."
+
+    export PGPASSWORD=${DB_PASSWORD}
+    if psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -f init-db.sql; then
+      echo "Comandos SQL ejecutados con éxito."
+      return 0
+    else
+      echo "Error al ejecutar comandos SQL. Intentando de nuevo en $retry_interval segundos..."
+      sleep $retry_interval
+      attempt=$((attempt + 1))
+    fi
+  done
+
+  echo "Falló la ejecución de comandos SQL después de $max_retries intentos."
+  return 1
+}
+
+# Ejecutar comandos SQL en la base de datos con reintentos
+echo "Ejecutando comandos SQL en la base de datos..."
+execute_sql_with_retries
+
+sleep 5
+
+# Reiniciar Odoo con módulos adicionales
+echo "Reiniciando Odoo con web_studio..."
+/usr/bin/odoo -c /etc/odoo/odoo.conf -i web_studio -u web
